Use gRPC moco-agent server.
cybozu-go/moco pull request #211
Opened 2021-02-26 09:43 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2021-03-04 05:30 UTC, masa213f requested changes
Please close the connections to agents here
https://github.com/cybozu-go/moco/blob/v0.7.0/controllers/mysqlcluster_controller.go#L181

and update this document.
https://github.com/cybozu-go/moco/blob/main/docs/example_mysql_cluster.md

2021-03-04 05:30 UTC, masa213f commented on Makefile
> +	# TODO
Could you update this rule?

2021-03-05 00:22 UTC, masa213f commented on Makefile
> +	bin/protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative agentrpc/agentrpc.proto
Let's use the variable.

```suggestion
	$(PROTOC) --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative agentrpc/agentrpc.proto
```

2021-03-05 01:12 UTC, kfyharukz commented on Makefile
> +	bin/protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative agentrpc/agentrpc.proto
🙇

2021-03-05 01:14 UTC, masa213f approved these changes
LGTM

2021-03-05 04:25 UTC, merged