Support k8s 1.22 and update dependencies
cybozu-go/moco pull request #338
Opened 2021-11-04 03:27 UTC by d-kuro

2021-11-04 03:55 UTC, d-kuro commented on .cr.yaml
> -release-name-template: "{{ .Name }}-chart-v{{ .Version }}"
This file was no longer needed.

2021-11-04 03:57 UTC, d-kuro commented on ct.yaml
> +check-version-increment: false
Chart releases are now done manually
Version increments are done at arbitrary times.
I disabled CI checks.

2021-11-05 05:20 UTC, zoetrope commented on .github/workflows/ci.yaml
> +        k8s-version: ["1.20.7", "1.21.1", "1.22.2"]
```suggestion
        k8s-version: ["1.20.7", "1.21.2", "1.22.2"]
```
Makefile uses `1.21.2`.

2021-11-05 06:03 UTC, zoetrope requested changes
I checked the changes in kubebuilder 3.2.0.
Please fix the followings.

- admissionReviewVersions should only support v1.
  - https://github.com/cybozu-go/moco/blob/04d00bbee82abccc907e69bad763d8b303bc330e/api/v1beta1/mysqlcluster_webhook.go#L25
  - https://github.com/cybozu-go/moco/blob/04d00bbee82abccc907e69bad763d8b303bc330e/api/v1beta1/mysqlcluster_webhook.go#L44
  - https://github.com/cybozu-go/moco/blob/3288f037e4efc1c8a7a041b88b90dce5d1f61f8d/api/v1beta1/backuppolicy_webhook.go#L26
- Please add `kubectl.kubernetes.io/default-container: manager` annotation to manager.yaml.
  - https://github.com/kubernetes-sigs/kubebuilder/blob/b6c36fa9eecb5f72680e7b8acf26cfc7a7c2fb50/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go#L69
- Call `defer GinkgoRecover()` webhook_suite_test.go.
  - https://github.com/kubernetes-sigs/kubebuilder/pull/2345

2021-11-05 06:06 UTC, zoetrope commented
Should we still support admissionReviewVersions/v1beta1?

2021-11-09 00:55 UTC, masa213f reviewed
I don't have any other comment. Please reflect zoetrope's comments.

2021-11-09 05:18 UTC, d-kuro commented
@zoetrope Thanks for reviewing it.
I Fixed:

* Call `GinkgoRecover`: https://github.com/cybozu-go/moco/pull/338/commits/57ee77a8170e9cb7ff893067f79fcbc0525b99cf
* Remove v1beta1 from admissionReviewVersions: https://github.com/cybozu-go/moco/pull/338/commits/c02b6d6d1b7dd649c01301468e8c76bedeedc9a6
* Add `default-container` annotation: https://github.com/cybozu-go/moco/pull/338/commits/16ca204da833f8bba0c0cfdc5fe2fd140f2a2902
* Use Kubernetes v1.21.2 for e2e tests: https://github.com/cybozu-go/moco/pull/338/commits/542aa901bbe6200ca14763a439a83d407fe45ed5

> Should we still support admissionReviewVersions/v1beta1?

I didn't think it necessary.

2021-11-11 09:04 UTC, zoetrope approved these changes
LGTM

2021-11-11 09:05 UTC, merged