Update controller to create Service resources
cybozu-go/moco pull request #52
Opened 2020-09-10 09:07 UTC by tomocy

This PR implements the feature to update a controller to reconcile services for primary and replica MySQL pods.

2020-09-10 10:30 UTC, kfyharukz requested changes

2020-09-10 10:30 UTC, kfyharukz commented on controllers/mysql_clustering_test.go
> +			name:  "LabelsAreWrong",
This test only covers the case "a read-only instance has a wrong label".
I think there is the case "a writable (it's the current primary) instance has a wrong label".  Isn't the test for this case needed?

2020-09-10 10:33 UTC, llamerada-jp commented
Isn't the length check needed at line 36 at infrastructure.go.

2020-09-10 10:34 UTC, llamerada-jp commented
Please remove `fmt.Println` at line 47 at mysql_accessor.go.

2020-09-11 01:51 UTC, entooone commented on Makefile
> +	mkdir -p bin
`./bin` is intended to store binaries other than those of `kubebuilder` , so we don't use `KUBEBUILDER_ASSETS` .

2020-09-11 02:35 UTC, llamerada-jp commented on Makefile
> +	mkdir -p bin
I see.

2020-09-11 02:46 UTC, llamerada-jp approved these changes
LGTM

2020-09-14 00:58 UTC, kfyharukz approved these changes
LGTM

2020-09-14 00:58 UTC, merged