Build fluent-bit container image.
cybozu-go/moco pull request #528
Opened 2023-05-17 04:08 UTC by d-kuro

2023-05-23 07:31 UTC, masa213f requested changes

2023-05-23 08:19 UTC, masa213f commented on .github/workflows/build-fluent-bit-container.yaml
> +          tags: ghcr.io/cybozu-go/moco/fluent-bit:${{ env.TAG }}
Sorry, the BRANCH tag is not used. It need not push the BRANCH tag.

Please delete the `BRANCH` file for fluent-bit.

2023-06-07 04:43 UTC, d-kuro commented on containers/fluent-bit/README.md
> +Docker images are available on [Quay.io](https://quay.io/repository/cybozu/fluent-bit)
Fixed: https://github.com/cybozu-go/moco/pull/528/commits/6227ff09880bdbd2551a1d80ccc37862a23be918

2023-06-07 04:44 UTC, d-kuro commented on containers/tag_exists
> +    echo "ok"
Thank you very much. Other bugs existed in the script, so I rewrote it.

https://github.com/cybozu-go/moco/pull/528/commits/875ff68ca69dc9799fa28405e95f14c48dfeb321

2023-06-07 04:44 UTC, d-kuro commented on .github/workflows/build-fluent-bit-container.yaml
> +          tags: ghcr.io/cybozu-go/moco/fluent-bit:${{ env.TAG }}
Remove it: https://github.com/cybozu-go/moco/pull/528/commits/e0b3475514bd760b967a56783dd83407923890c6

2023-06-07 06:01 UTC, d-kuro commented on containers/tag_exists
> +HTTP_STATUS=$(curl --head -H "Authorization: Bearer $TOKEN" -sSL -w "%{http_code}" "https://ghcr.io/v2/cybozu-go/moco/$NAME/manifests/$TAG" -o /dev/null)
Thanks!

https://github.com/cybozu-go/moco/pull/528/commits/21889fd8d4a6badbed4e36cab758536290cbc357

2023-06-13 09:14 UTC, masa213f requested changes

2023-06-21 06:23 UTC, d-kuro commented
@masa213f 
Thanks for the review.
Please review again as I have made the corrections in the following commit 🙏 

https://github.com/cybozu-go/moco/pull/528/commits/aa5c8356c736bb345c5138175099996a21f471e2

2023-06-23 02:43 UTC, masa213f approved these changes
LGTM

2023-06-23 02:45 UTC, merged