issue-745: Set timeoutSeconds to 50sec
cybozu-go/moco pull request #746
Opened 2024-10-04 08:57 UTC by shunki-fujita

https://github.com/cybozu-go/moco/issues/745

2024-10-04 10:12 UTC, ymmt2005 requested changes

2024-10-04 10:12 UTC, ymmt2005 commented on clustering/operations.go
>  	}
I think we can loop this if `err` is `dbop.ErrTimeout`.
https://github.com/cybozu-go/moco/blob/main/pkg/dbop/replication.go#L69

2024-10-04 10:12 UTC, ymmt2005 commented on clustering/operations.go
>  	}
ditto

2024-10-07 04:37 UTC, shunki-fujita commented on clustering/operations.go
>  	}
Looping here will prevent updateStatus from being called, so leave the looping to managerProcess.

2024-10-07 04:39 UTC, ymmt2005 approved these changes
LGTM

2024-10-07 04:39 UTC, merged