Add clone test
cybozu-go/moco pull request #82
Opened 2020-10-15 07:17 UTC by zoetrope

Signed-off-by: zoetrope <a.ikezoe@gmail.com>

2020-10-20 07:16 UTC, kfyharukz requested changes

2020-10-20 07:16 UTC, kfyharukz commented on controllers/mysqlcluster_controller_test.go
> +		It("should create cron job", func() {
Some additional tests are needed, such as the CronJob has the correct command with the agent token.

2020-10-20 07:16 UTC, kfyharukz commented on controllers/mysqlcluster_controller_test.go
> +			By("setting the size of 70% of the request", func() {
`70%` seems to be a magic number.  Should it be a constant?

2020-10-20 07:16 UTC, kfyharukz commented on controllers/mysqlcluster_controller_test.go
> +		It("should return error, when template does not contain mysqld container", func() {
This constraint doesn't appear in the docs.  We should write it in `crd_mysqlcluster.md`.

2020-10-20 07:16 UTC, kfyharukz commented on controllers/mysqlcluster_controller_test.go
> +		It("should return error, when template contains agent container", func() {
ditto

2020-10-20 07:16 UTC, kfyharukz commented on controllers/mysqlcluster_controller_test.go
> +			Expect(testClaim).ShouldNot(BeNil())
The `test-volume` should be checked as having the correct value, shouldn't it?

2020-10-20 07:28 UTC, umezawatakeshi commented on controllers/mysqlcluster_controller_test.go
> +			Expect(createdReplicaService.Spec.Ports).Should(HaveLen(2))
Is it intended to only check the length of "createdReplicaService" and not its content?

2020-10-20 07:30 UTC, umezawatakeshi commented on controllers/mysqlcluster_controller_test.go
>  			Expect(createdReplicaService.Spec.Ports).Should(HaveLen(2))
ditto

2020-10-22 02:14 UTC, kfyharukz approved these changes
LGTM

2020-10-22 02:14 UTC, merged